# ✅ MySQL Deployment 추가
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: hello

---

# ✅ MySQL Service 그대로 유지 (단, selector 추가)
apiVersion: v1
kind: Service
metadata:
  name: k8s-external-user-mysql-service
spec:
  selector:
    app: mysql   # ← 이 부분 추가!
  ports:
    - port: 3307
      targetPort: 3306
