apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-user-deployment-v7
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend-user
      ver: v7
  template:
    metadata:
      labels:
        app: k8s-backend-user
        ver: v7
    spec:
      containers:
      - name: k8s-backend-user
        image: danajlim/k8s-backend-user:0.0.7
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
        - containerPort: 8080

        # ✅ Liveness Probe 설정 (컨테이너 생존 여부 확인)
        livenessProbe:
          httpGet:
            path: /backend/user/v1/k8s/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 3

        # ✅ Readiness Probe 설정 (트래픽 수신 준비 여부 확인)
        readinessProbe:
          httpGet:
            path: /backend/user/v1/k8s/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3

        volumeMounts:
          - name: backend-user-config-volume
            mountPath: /etc/config
            readOnly: true
          - name: backend-user-secret-volume
            mountPath: /etc/secret
            readOnly: true

      volumes:
      - name: backend-user-config-volume
        configMap:
          name: backend-user-config
          items:
            - key: application-dev.yml
              path: application-dev.yml
      - name: backend-user-secret-volume
        secret:
          secretName: backend-user-secret
          items:
            - key: application-secret.yml
              path: application-secret.yml
